title: "Cycle.js"
author: "Andre Staltz"
description: "A functional and reactive JavaScript framework for predictable code"
more: "read more"
url: "http://cycle.js.org/"
permalink: none

excerpt_separator: "\n\n\n"
defaults: [{scope: {path: ""}, values: {layout: "default"}}, {scope: {path: "", type: "posts"}, values: {comments: true}}]
gems:
  - octopress-autoprefixer
  - kramdown
  - jekyll-redirect-from
whitelist:
  - jekyll-redirect-from
